AWSTemplateFormatVersion: 2010-09-09
Description: Create ECS container instance that joins a specified cluster automatically

Parameters:
  ClusterName:
    Description: Cluster name
    Type: String
    AllowedPattern: "^ecs-workshop-user-[0-9]+$"
  EC2InstanceType:
    Type: String
    # We need these to be xlarge so we don't run out of ENIs
    Default: t3a.xlarge
    Description: EC2 instance type
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
    Description: EC2 AMI ID

Resources:
  EcsInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT5M
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref EC2InstanceType
      IamInstanceProfile:
        Fn::ImportValue: ecsworkshop:EcsInstanceProfile
      Monitoring: true
      SubnetId:
        Fn::ImportValue: ecsworkshop:PrivateSubnetOne
      SecurityGroupIds:
        - Fn::ImportValue: ecsworkshop:InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: !Ref ClusterName
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -ex
            echo "ECS_CLUSTER=${ClusterName}" >> /etc/ecs/ecs.config
            yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm \
                           https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.amzn1.noarch.rpm
            systemctl enable amazon-ssm-agent
            systemctl start amazon-ssm-agent
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EcsInstance --region ${AWS::Region}
